service: aas-cidr-ranges
frameworkVersion: '>=3.0.0 <4.0.0'

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    apiKeys:
      - value: THIS_IS_A_PUBLIC_KEY
        description: This is a key placed in public domain intentionally to put as part of the 'x-api-key' header for access
    usagePlan:
      quota:
        limit: 100
        offset: 0
        period: DAY
      throttle:
        burstLimit: 25
        rateLimit: 10

plugins:
  - serverless-python-requirements

functions:
  belong:
    handler: handler.belong
    events:
      - http:
          path: /belong
          method: get
          private: true
    timeout: 10
    memorySize: 256
