name: Deploy to AWS

on:
  push:
    branches:
      - master
  schedule:
    - cron: '50 22 * * *'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.11]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0

      - name: Set up Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 #v4.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - name: Serverless Deploy
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETACCESSKEY }}
