name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: python:3.8-slim
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Serverless Deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETACCESSKEY }}
